Systems manager jh2
CrowdStrike/Cloud-AWS pull request #49
Opened 2021-03-15 22:27 UTC by jhseceng

Resolved conflict. Please review

2021-03-15 22:48 UTC, shawndwells requested changes
* Should systems-manager/Packaging-utilities/examples/linux-sensor-binary/CS_AMAZON/install.sh be dropped? Worried we keep re-creating bespoke bash installation scripts instead of using the centralized ones

2021-03-15 22:48 UTC, shawndwells commented on systems-manager/Packaging-utilities/examples/linux-sensor-binary/CS_AMAZON/install.sh
> +filename="falcon-sensor-6.16.0-11308.amzn2.x86_64.rpm"
Hard coded filename

2021-03-15 22:48 UTC, shawndwells commented on systems-manager/Packaging-utilities/examples/linux-sensor-binary/packager.py
> +        print("Nothing to do ... specify region + bucket or region + bucket + package_name")
How are these options received? Can an example be given?

eg ``specify a region with the --region <region> flag``

2021-03-15 22:48 UTC, shawndwells commented on systems-manager/Packaging-utilities/examples/linux-sensor-download/CS_AMAZON/install.sh
>     service falcon-sensor restart
Can more identifiable variable names be used?

2021-03-15 22:48 UTC, shawndwells commented on systems-manager/Packaging-utilities/examples/linux-sensor-download/CS_AMAZON/install.sh
> +fi
This logic will break for the pending s390x release

2021-03-15 22:48 UTC, shawndwells commented on systems-manager/documentation/AWS-Systems-Manager-Intro.md
> +TARGET_VER=<<minimum version>> example format =5.38.10404
```suggestion
Update the following variables at the top of the installation script:

```
filename=<<filename of the rpm package>>
TARGET_VER=<<minimum version>> example format =5.38.10404
```
```

2021-03-15 22:48 UTC, shawndwells commented on systems-manager/documentation/AWS-Systems-Manager-Intro.md
> +  echo "Falcon-sensor not found"
```suggestion
  echo "Package falcon-sensor not found"
```

2021-03-15 22:48 UTC, shawndwells commented
Also looks like there are several merges included. You may want to rebase your branch and squash your incremental commits.

2021-03-16 21:15 UTC, closed without merging

2021-03-16 21:15 UTC, jhseceng commented
Creating new pull request after further updates